"""YAML config loader for the diary pipeline.

Single config file at ``pipeline/config/pipeline.yaml`` (gitignored).
Generated by ``desktop.bootstrap`` on first run; thereafter read-only.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


class ConfigError(ValueError):
    """Raised when the config file is missing keys or malformed."""


def _require(d: dict, key: str, path: str) -> Any:
    if key not in d:
        raise ConfigError(f"Missing required config key: {path}")
    return d[key]


@dataclass(frozen=True)
class RemarkableConfig:
    diary_notebook_name: str
    ssh_host: str
    ssh_user: str

    @classmethod
    def from_dict(cls, d: dict) -> RemarkableConfig:
        return cls(
            diary_notebook_name=_require(d, "diary_notebook_name", "remarkable.diary_notebook_name"),
            ssh_host=_require(d, "ssh_host", "remarkable.ssh_host"),
            ssh_user=_require(d, "ssh_user", "remarkable.ssh_user"),
        )


@dataclass(frozen=True)
class PiConfig:
    ssh_host: str
    ssh_port: int
    ssh_user: str
    ssh_key: str
    inbox_path: str

    @classmethod
    def from_dict(cls, d: dict) -> PiConfig:
        return cls(
            ssh_host=_require(d, "ssh_host", "pi.ssh_host"),
            ssh_port=int(_require(d, "ssh_port", "pi.ssh_port")),
            ssh_user=_require(d, "ssh_user", "pi.ssh_user"),
            ssh_key=_require(d, "ssh_key", "pi.ssh_key"),
            inbox_path=_require(d, "inbox_path", "pi.inbox_path"),
        )


@dataclass(frozen=True)
class FolderRoute:
    notebook: str
    title_format: str
    split: bool = False
    labels: tuple[str, ...] = ()


# rM 폴더명 → 라우팅. config의 tomboy.folders가 이를 덮어쓴다.
DEFAULT_FOLDER_ROUTES: dict[str, FolderRoute] = {
    "Diary": FolderRoute("일기", "{date} 리마커블([{unit_key}])"),
    "Notes": FolderRoute("기록", "{date} 리마커블([{unit_key}])"),
    "Slip-Notes": FolderRoute(
        "[0] Slip-Box",
        "{datetime} 리마커블 {label}([{unit_key}])",
        split=True,
        labels=("上", "下"),
    ),
}
# 알 수 없는 rM 폴더는 Notes처럼 처리(전체 페이지, 분할 없음).
_FALLBACK_FOLDER = "Notes"


@dataclass(frozen=True)
class TomboyConfig:
    folders: dict[str, FolderRoute]
    diary_notebook_name: str = "일기"
    title_format: str = "{date} 리마커블([{page_uuid}])"

    def route_for(self, source_folder: str | None) -> FolderRoute:
        if source_folder and source_folder in self.folders:
            return self.folders[source_folder]
        return self.folders.get(
            _FALLBACK_FOLDER, FolderRoute("기록", "{date} 리마커블([{unit_key}])")
        )

    @classmethod
    def from_dict(cls, d: dict) -> TomboyConfig:
        folders: dict[str, FolderRoute] = dict(DEFAULT_FOLDER_ROUTES)
        legacy_nb = d.get("diary_notebook_name")
        legacy_tf = d.get("title_format")
        # 레거시 단일 폴더 키 → Diary 엔트리 오버라이드(하위호환).
        if legacy_nb or legacy_tf:
            base = folders["Diary"]
            folders["Diary"] = FolderRoute(
                notebook=legacy_nb or base.notebook,
                title_format=legacy_tf or base.title_format,
            )
        # 명시적 folders 맵이 최종 오버라이드.
        for name, fd in (d.get("folders") or {}).items():
            folders[name] = FolderRoute(
                notebook=_require(fd, "notebook", f"tomboy.folders.{name}.notebook"),
                title_format=_require(
                    fd, "title_format", f"tomboy.folders.{name}.title_format"
                ),
                split=bool(fd.get("split", False)),
                labels=tuple(fd.get("labels", ()) or ()),
            )
        return cls(
            folders=folders,
            diary_notebook_name=legacy_nb or "일기",
            title_format=legacy_tf or "{date} 리마커블([{page_uuid}])",
        )


@dataclass(frozen=True)
class LocalVlmConfig:
    model_id: str
    quantization: str = "4bit"
    max_new_tokens: int = 2048
    system_prompt_path: str = "config/prompts/diary-ko.txt"

    @classmethod
    def from_dict(cls, d: dict) -> LocalVlmConfig:
        return cls(
            model_id=_require(d, "model_id", "ocr.local_vlm.model_id"),
            quantization=d.get("quantization", "4bit"),
            max_new_tokens=int(d.get("max_new_tokens", 2048)),
            system_prompt_path=d.get(
                "system_prompt_path", "config/prompts/diary-ko.txt"
            ),
        )


@dataclass(frozen=True)
class ClaudeConfig:
    service_url: str
    service_token: str
    model: str  # 빈 문자열 = claude-service 기본값에 위임
    effort: str
    system_prompt_path: str

    @classmethod
    def from_dict(cls, d: dict) -> ClaudeConfig:
        return cls(
            service_url=_require(d, "service_url", "ocr.claude.service_url"),
            service_token=_require(d, "service_token", "ocr.claude.service_token"),
            model=d.get("model", ""),
            effort=d.get("effort", "high"),
            system_prompt_path=d.get(
                "system_prompt_path", "config/prompts/diary-ko.txt"
            ),
        )


@dataclass(frozen=True)
class OcrConfig:
    backend: str
    local_vlm: LocalVlmConfig | None = None
    claude: ClaudeConfig | None = None

    @classmethod
    def from_dict(cls, d: dict) -> OcrConfig:
        backend = _require(d, "backend", "ocr.backend")
        local_vlm = LocalVlmConfig.from_dict(d["local_vlm"]) if "local_vlm" in d else None
        claude = ClaudeConfig.from_dict(d["claude"]) if "claude" in d else None
        if backend == "claude" and claude is None:
            raise ConfigError("ocr.backend is 'claude' but ocr.claude subsection is missing")
        if backend == "local_vlm" and local_vlm is None:
            raise ConfigError("ocr.backend is 'local_vlm' but ocr.local_vlm subsection is missing")
        return cls(backend=backend, local_vlm=local_vlm, claude=claude)


@dataclass(frozen=True)
class DesktopConfig:
    data_dir: str = "~/.local/share/tomboy-pipeline"

    @classmethod
    def from_dict(cls, d: dict) -> DesktopConfig:
        return cls(data_dir=d.get("data_dir", "~/.local/share/tomboy-pipeline"))


@dataclass(frozen=True)
class Config:
    firebase_uid: str
    firebase_service_account: str
    dropbox_refresh_token: str
    dropbox_app_key: str
    remarkable: RemarkableConfig
    pi: PiConfig
    desktop: DesktopConfig
    tomboy: TomboyConfig
    ocr: OcrConfig

    @property
    def data_dir(self) -> Path:
        return Path(self.desktop.data_dir).expanduser().resolve()

    @classmethod
    def from_dict(cls, d: dict) -> Config:
        if not d:
            raise ConfigError("Config is empty")
        return cls(
            firebase_uid=_require(d, "firebase_uid", "firebase_uid"),
            firebase_service_account=_require(d, "firebase_service_account", "firebase_service_account"),
            dropbox_refresh_token=d.get("dropbox_refresh_token", ""),
            dropbox_app_key=d.get("dropbox_app_key", ""),
            remarkable=RemarkableConfig.from_dict(_require(d, "remarkable", "remarkable")),
            pi=PiConfig.from_dict(_require(d, "pi", "pi")),
            desktop=DesktopConfig.from_dict(d.get("desktop", {})),
            tomboy=TomboyConfig.from_dict(d.get("tomboy", {})),
            ocr=OcrConfig.from_dict(_require(d, "ocr", "ocr")),
        )

    @staticmethod
    def example_yaml() -> str:
        return _EXAMPLE_YAML


_EXAMPLE_YAML = """\
# Generated by `python -m desktop.bootstrap`. Do not edit by hand unless
# you know what you're doing — bootstrap is idempotent.

firebase_uid: "dbx-REPLACE_ME"
firebase_service_account: "/path/to/firebase-sa.json"
dropbox_refresh_token: "REPLACE_ME"
dropbox_app_key: "REPLACE_ME"

remarkable:
  diary_notebook_name: "Diary"
  ssh_host: "rm.local"
  ssh_user: "root"

pi:
  ssh_host: "pi.example.com"
  ssh_port: 2222
  ssh_user: "diary-sync"
  ssh_key: "~/.ssh/id_ed25519_diary"
  inbox_path: "~/diary/inbox"

desktop:
  data_dir: "~/.local/share/tomboy-pipeline"

tomboy:
  diary_notebook_name: "일기"
  title_format: "{date} 리마커블([{page_uuid}])"

ocr:
  backend: "claude"
  # claude-service (구독 OAuth 재사용) 경유. backend가 "claude"일 때만 사용.
  claude:
    service_url: "http://localhost:7842"
    service_token: "REPLACE_ME"  # claude-service Bearer 토큰
    model: ""                    # 빈 값 = claude-service 기본 모델
    effort: "high"
    system_prompt_path: "config/prompts/diary-ko.txt"
  # 로컬 GPU(Qwen2.5-VL) 경로. backend가 "local_vlm"일 때만 사용.
  # claude → local_vlm 전환은 위 backend 한 줄만 변경.
  local_vlm:
    model_id: "Qwen/Qwen2.5-VL-7B-Instruct"
    quantization: "4bit"
    max_new_tokens: 2048
    system_prompt_path: "config/prompts/diary-ko.txt"
"""


def load_config_from_string(s: str) -> Config:
    data = yaml.safe_load(s) or {}
    return Config.from_dict(data)


def load_config(path: Path | str) -> Config:
    p = Path(path)
    if not p.exists():
        raise ConfigError(f"Config file not found: {p}")
    return load_config_from_string(p.read_text(encoding="utf-8"))
