"""YAML config loader for the diary pipeline.

Single config file at ``pipeline/config/pipeline.yaml`` (gitignored).
Generated by ``desktop.bootstrap`` on first run; thereafter read-only.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


class ConfigError(ValueError):
    """Raised when the config file is missing keys or malformed."""


def _require(d: dict, key: str, path: str) -> Any:
    if key not in d:
        raise ConfigError(f"Missing required config key: {path}")
    return d[key]


@dataclass(frozen=True)
class RemarkableConfig:
    diary_notebook_name: str
    ssh_host: str
    ssh_user: str

    @classmethod
    def from_dict(cls, d: dict) -> RemarkableConfig:
        return cls(
            diary_notebook_name=_require(d, "diary_notebook_name", "remarkable.diary_notebook_name"),
            ssh_host=_require(d, "ssh_host", "remarkable.ssh_host"),
            ssh_user=_require(d, "ssh_user", "remarkable.ssh_user"),
        )


@dataclass(frozen=True)
class PiConfig:
    ssh_host: str
    ssh_port: int
    ssh_user: str
    ssh_key: str
    inbox_path: str

    @classmethod
    def from_dict(cls, d: dict) -> PiConfig:
        return cls(
            ssh_host=_require(d, "ssh_host", "pi.ssh_host"),
            ssh_port=int(_require(d, "ssh_port", "pi.ssh_port")),
            ssh_user=_require(d, "ssh_user", "pi.ssh_user"),
            ssh_key=_require(d, "ssh_key", "pi.ssh_key"),
            inbox_path=_require(d, "inbox_path", "pi.inbox_path"),
        )


@dataclass(frozen=True)
class TomboyConfig:
    diary_notebook_name: str = "일기"
    title_format: str = "{date} 리마커블([{page_uuid}])"

    @classmethod
    def from_dict(cls, d: dict) -> TomboyConfig:
        return cls(
            diary_notebook_name=d.get("diary_notebook_name", "일기"),
            title_format=d.get("title_format", "{date} 리마커블([{page_uuid}])"),
        )


@dataclass(frozen=True)
class LocalVlmConfig:
    model_id: str
    quantization: str
    max_new_tokens: int
    system_prompt_path: str


@dataclass(frozen=True)
class OcrConfig:
    backend: str
    local_vlm: LocalVlmConfig | None = None

    @classmethod
    def from_dict(cls, d: dict) -> OcrConfig:
        backend = _require(d, "backend", "ocr.backend")
        local_vlm = None
        if "local_vlm" in d:
            v = d["local_vlm"]
            local_vlm = LocalVlmConfig(
                model_id=_require(v, "model_id", "ocr.local_vlm.model_id"),
                quantization=v.get("quantization", "4bit"),
                max_new_tokens=int(v.get("max_new_tokens", 2048)),
                system_prompt_path=v.get("system_prompt_path", "config/prompts/diary-ko.txt"),
            )
        return cls(backend=backend, local_vlm=local_vlm)


@dataclass(frozen=True)
class DesktopConfig:
    data_dir_raw: str = "~/.local/share/tomboy-pipeline"

    @classmethod
    def from_dict(cls, d: dict) -> DesktopConfig:
        return cls(data_dir_raw=d.get("data_dir", "~/.local/share/tomboy-pipeline"))


@dataclass(frozen=True)
class Config:
    firebase_uid: str
    firebase_service_account: str
    dropbox_refresh_token: str
    dropbox_app_key: str
    remarkable: RemarkableConfig
    pi: PiConfig
    desktop: DesktopConfig
    tomboy: TomboyConfig
    ocr: OcrConfig

    @property
    def data_dir(self) -> Path:
        return Path(self.desktop.data_dir_raw).expanduser().resolve()

    @classmethod
    def from_dict(cls, d: dict) -> Config:
        if not d:
            raise ConfigError("Config is empty")
        return cls(
            firebase_uid=_require(d, "firebase_uid", "firebase_uid"),
            firebase_service_account=_require(d, "firebase_service_account", "firebase_service_account"),
            dropbox_refresh_token=_require(d, "dropbox_refresh_token", "dropbox_refresh_token"),
            dropbox_app_key=_require(d, "dropbox_app_key", "dropbox_app_key"),
            remarkable=RemarkableConfig.from_dict(_require(d, "remarkable", "remarkable")),
            pi=PiConfig.from_dict(_require(d, "pi", "pi")),
            desktop=DesktopConfig.from_dict(d.get("desktop", {})),
            tomboy=TomboyConfig.from_dict(d.get("tomboy", {})),
            ocr=OcrConfig.from_dict(_require(d, "ocr", "ocr")),
        )

    @staticmethod
    def example_yaml() -> str:
        return _EXAMPLE_YAML


_EXAMPLE_YAML = """\
# Generated by `python -m desktop.bootstrap`. Do not edit by hand unless
# you know what you're doing — bootstrap is idempotent.

firebase_uid: "dbx-REPLACE_ME"
firebase_service_account: "/path/to/firebase-sa.json"
dropbox_refresh_token: "REPLACE_ME"
dropbox_app_key: "REPLACE_ME"

remarkable:
  diary_notebook_name: "Diary"
  ssh_host: "rm.local"
  ssh_user: "root"

pi:
  ssh_host: "pi.example.com"
  ssh_port: 2222
  ssh_user: "diary-sync"
  ssh_key: "~/.ssh/id_ed25519_diary"
  inbox_path: "~/diary/inbox"

desktop:
  data_dir: "~/.local/share/tomboy-pipeline"

tomboy:
  diary_notebook_name: "일기"
  title_format: "{date} 리마커블([{page_uuid}])"

ocr:
  backend: "local_vlm"
  local_vlm:
    model_id: "Qwen/Qwen2.5-VL-7B-Instruct"
    quantization: "4bit"
    max_new_tokens: 2048
    system_prompt_path: "config/prompts/diary-ko.txt"
"""


def load_config_from_string(s: str) -> Config:
    data = yaml.safe_load(s) or {}
    return Config.from_dict(data)


def load_config(path: Path | str) -> Config:
    p = Path(path)
    if not p.exists():
        raise ConfigError(f"Config file not found: {p}")
    return load_config_from_string(p.read_text(encoding="utf-8"))
