/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope;

import { build, files, version } from '$service-worker';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

const CACHE_NAME = `tomboy-web-${version}`;

// Assets generated by the build process + static files
const ASSETS = [...build, ...files];

// ── Firebase Cloud Messaging ─────────────────────────────────────────────
// Vite inlines `import.meta.env.PUBLIC_*` at build. These values are public
// by design (Firebase web config); security comes from Firestore rules and
// authenticated requests, not from secrecy of the apiKey.
const firebaseApp = initializeApp({
	apiKey: import.meta.env.PUBLIC_FIREBASE_API_KEY,
	authDomain: import.meta.env.PUBLIC_FIREBASE_AUTH_DOMAIN,
	projectId: import.meta.env.PUBLIC_FIREBASE_PROJECT_ID,
	storageBucket: import.meta.env.PUBLIC_FIREBASE_STORAGE_BUCKET,
	messagingSenderId: import.meta.env.PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
	appId: import.meta.env.PUBLIC_FIREBASE_APP_ID
});
const messaging = getMessaging(firebaseApp);

// Background-message handler. Some browsers (notably WebKit-based on iOS)
// will auto-display FCM `notification` payloads, others require explicit
// `showNotification`. Calling it explicitly here guarantees consistency.
onBackgroundMessage(messaging, (payload) => {
	const title = payload.notification?.title ?? '일정';
	const body = payload.notification?.body ?? '';
	const data = payload.data ?? {};
	void self.registration.showNotification(title, {
		body,
		icon: '/icons/icon.svg',
		badge: '/icons/icon.svg',
		tag: data.itemId ?? undefined,
		data
	});
});

self.addEventListener('notificationclick', (event) => {
	event.notification.close();
	const data = (event.notification.data ?? {}) as { scheduleNoteGuid?: string };
	const target = data.scheduleNoteGuid
		? `/note/${data.scheduleNoteGuid}?from=notes`
		: '/';
	event.waitUntil(
		(async () => {
			const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
			// If a window for this app is already open, focus it and navigate.
			for (const client of all) {
				if ('focus' in client) {
					await (client as WindowClient).focus();
					await (client as WindowClient).navigate(target).catch(() => {});
					return;
				}
			}
			await self.clients.openWindow(target);
		})()
	);
});

// ── Cache lifecycle (existing) ───────────────────────────────────────────

self.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll(ASSETS))
			.then(() => self.skipWaiting())
	);
});

self.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== CACHE_NAME) {
					await caches.delete(key);
				}
			}
			await self.clients.claim();
		})
	);
});

self.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Don't cache Dropbox API calls
	if (url.hostname.includes('dropbox')) return;

	// Don't cache external requests
	if (url.origin !== self.location.origin) return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);

			// Try cache first for build assets (they're versioned/immutable)
			if (ASSETS.includes(url.pathname)) {
				const cached = await cache.match(event.request);
				if (cached) return cached;
			}

			// Network first for navigation requests
			try {
				const response = await fetch(event.request);
				// Cache successful responses
				if (response.status === 200) {
					cache.put(event.request, response.clone());
				}
				return response;
			} catch {
				// Offline — serve from cache
				const cached = await cache.match(event.request);
				if (cached) return cached;

				// For navigation requests, return the cached index page (SPA fallback)
				if (event.request.mode === 'navigate') {
					const fallback = await cache.match('/');
					if (fallback) return fallback;
				}

				return new Response('Offline', { status: 503 });
			}
		})()
	);
});
