/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope;

import { build, files, version } from '$service-worker';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

const CACHE_NAME = `tomboy-web-${version}`;
const SW_VERSION_TAG = `tomboy-sw-v3-debug-${version}`;
console.info('[sw] script loaded', SW_VERSION_TAG);

// Assets generated by the build process + static files
const ASSETS = [...build, ...files];

// ── Firebase Cloud Messaging ─────────────────────────────────────────────
// Vite inlines `import.meta.env.PUBLIC_*` at build. These values are public
// by design (Firebase web config); security comes from Firestore rules and
// authenticated requests, not from secrecy of the apiKey.
const firebaseApp = initializeApp({
	apiKey: import.meta.env.PUBLIC_FIREBASE_API_KEY,
	authDomain: import.meta.env.PUBLIC_FIREBASE_AUTH_DOMAIN,
	projectId: import.meta.env.PUBLIC_FIREBASE_PROJECT_ID,
	storageBucket: import.meta.env.PUBLIC_FIREBASE_STORAGE_BUCKET,
	messagingSenderId: import.meta.env.PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
	appId: import.meta.env.PUBLIC_FIREBASE_APP_ID
});
const messaging = getMessaging(firebaseApp);

// Diagnostic mode: unconditionally show a notification on every push event.
// This isolates "is the push event even reaching the SW?" from any
// payload-parsing or FCM-SDK issues. If THIS doesn't display when FCM
// reports success, then either the SW running on the device is stale
// (older deploy without push handlers), or the push event isn't being
// dispatched to this SW at all (Apple-side issue / OS setting).
self.addEventListener('push', (event) => {
	let preview = '<no data>';
	try {
		preview = event.data?.text() ?? '<no data>';
	} catch (err) {
		preview = `<unreadable: ${String(err)}>`;
	}
	console.info('[sw] raw push event fired', { preview, version: SW_VERSION_TAG });

	let title = '🔔 PUSH RECEIVED';
	let body = `SW ${version} got a push event.`;
	let tag: string | undefined = `debug-${Date.now()}`;
	try {
		const data = JSON.parse(preview);
		title = data?.notification?.title ?? title;
		body = data?.notification?.body ?? body;
		tag = data?.data?.itemId ?? data?.data?.test ?? tag;
	} catch {
		/* not JSON — keep debug defaults */
	}

	event.waitUntil(
		self.registration.showNotification(title, {
			body,
			icon: '/icons/icon.svg',
			badge: '/icons/icon.svg',
			tag,
			requireInteraction: false
		})
	);
});

self.addEventListener('pushsubscriptionchange', (event) => {
	console.warn('[sw] pushsubscriptionchange — token needs refresh', event);
});

// Background-message handler (FCM SDK). Some browsers (notably WebKit-based
// on iOS) auto-display FCM `notification` payloads; others require
// explicit `showNotification`. Calling it explicitly here guarantees
// consistency.
onBackgroundMessage(messaging, (payload) => {
	console.info('[sw] FCM background push', payload);
	const title = payload.notification?.title ?? '일정';
	const body = payload.notification?.body ?? '';
	const data = payload.data ?? {};
	void self.registration.showNotification(title, {
		body,
		icon: '/icons/icon.svg',
		badge: '/icons/icon.svg',
		tag: data.itemId ?? data.test ?? undefined,
		data
	});
});

self.addEventListener('notificationclick', (event) => {
	event.notification.close();
	const data = (event.notification.data ?? {}) as { scheduleNoteGuid?: string };
	const target = data.scheduleNoteGuid
		? `/note/${data.scheduleNoteGuid}?from=notes`
		: '/';
	event.waitUntil(
		(async () => {
			const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
			// If a window for this app is already open, focus it and navigate.
			for (const client of all) {
				if ('focus' in client) {
					await (client as WindowClient).focus();
					await (client as WindowClient).navigate(target).catch(() => {});
					return;
				}
			}
			await self.clients.openWindow(target);
		})()
	);
});

// ── Cache lifecycle (existing) ───────────────────────────────────────────

self.addEventListener('install', (event) => {
	// Don't `cache.addAll(ASSETS)` here — it pre-fetches every build asset
	// in parallel, and a single 404/timeout (or the network being slow on
	// a freshly-installed PWA) rejects the whole install and prevents SW
	// activation. That left `serviceWorker.ready` hanging during the
	// notification-enable flow. Activation should be fast and unconditional;
	// real caching is done lazily by the fetch handler below.
	event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== CACHE_NAME) {
					await caches.delete(key);
				}
			}
			await self.clients.claim();
		})
	);
});

self.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Don't cache Dropbox API calls
	if (url.hostname.includes('dropbox')) return;

	// Don't cache external requests
	if (url.origin !== self.location.origin) return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);

			// Try cache first for build assets (they're versioned/immutable)
			if (ASSETS.includes(url.pathname)) {
				const cached = await cache.match(event.request);
				if (cached) return cached;
			}

			// Network first for navigation requests
			try {
				const response = await fetch(event.request);
				// Cache successful responses
				if (response.status === 200) {
					cache.put(event.request, response.clone());
				}
				return response;
			} catch {
				// Offline — serve from cache
				const cached = await cache.match(event.request);
				if (cached) return cached;

				// For navigation requests, return the cached index page (SPA fallback)
				if (event.request.mode === 'navigate') {
					const fallback = await cache.match('/');
					if (fallback) return fallback;
				}

				return new Response('Offline', { status: 503 });
			}
		})()
	);
});
