/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope;

import { build, files, version } from '$service-worker';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';
// IMPORTANT: SvelteKit only inlines `PUBLIC_*` env vars when imported via
// the `$env/*` virtual module. Inside a service worker, `import.meta.env`
// falls back to Vite defaults (VITE_*) and our PUBLIC_* values come out
// as `undefined`, which silently breaks `initializeApp` and prevents the
// SW from ever activating.
import {
	PUBLIC_FIREBASE_API_KEY,
	PUBLIC_FIREBASE_APP_ID,
	PUBLIC_FIREBASE_AUTH_DOMAIN,
	PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
	PUBLIC_FIREBASE_PROJECT_ID,
	PUBLIC_FIREBASE_STORAGE_BUCKET
} from '$env/static/public';

const CACHE_NAME = `tomboy-web-${version}`;
const SW_VERSION_TAG = `tomboy-sw-v4-${version}`;
console.info('[sw] script loaded', SW_VERSION_TAG);

// Assets generated by the build process + static files
const ASSETS = [...build, ...files];

// ── Firebase Cloud Messaging ─────────────────────────────────────────────
// These values are public by design (Firebase web config); security comes
// from Firestore rules and authenticated requests, not from secrecy of the
// apiKey.
const firebaseApp = initializeApp({
	apiKey: PUBLIC_FIREBASE_API_KEY,
	authDomain: PUBLIC_FIREBASE_AUTH_DOMAIN,
	projectId: PUBLIC_FIREBASE_PROJECT_ID,
	storageBucket: PUBLIC_FIREBASE_STORAGE_BUCKET,
	messagingSenderId: PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
	appId: PUBLIC_FIREBASE_APP_ID
});
const messaging = getMessaging(firebaseApp);

self.addEventListener('pushsubscriptionchange', (event) => {
	console.warn('[sw] pushsubscriptionchange — token needs refresh', event);
});

// FCM background message — log only. iOS Web Push REQUIRES the payload's
// `notification.title/body` and the OS auto-displays it; calling
// `showNotification` here too produces a duplicate. The handler still
// matters for `notificationclick` data routing and any non-iOS targets.
onBackgroundMessage(messaging, (payload) => {
	console.info('[sw] FCM background push', payload);
});

self.addEventListener('notificationclick', (event) => {
	event.notification.close();
	const data = (event.notification.data ?? {}) as { scheduleNoteGuid?: string };
	const target = data.scheduleNoteGuid
		? `/note/${data.scheduleNoteGuid}?from=notes`
		: '/';
	event.waitUntil(
		(async () => {
			const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
			// If a window for this app is already open, focus it and navigate.
			for (const client of all) {
				if ('focus' in client) {
					await (client as WindowClient).focus();
					await (client as WindowClient).navigate(target).catch(() => {});
					return;
				}
			}
			await self.clients.openWindow(target);
		})()
	);
});

// ── Cache lifecycle (existing) ───────────────────────────────────────────

self.addEventListener('install', (event) => {
	// Don't `cache.addAll(ASSETS)` here — it pre-fetches every build asset
	// in parallel, and a single 404/timeout (or the network being slow on
	// a freshly-installed PWA) rejects the whole install and prevents SW
	// activation. That left `serviceWorker.ready` hanging during the
	// notification-enable flow. Activation should be fast and unconditional;
	// real caching is done lazily by the fetch handler below.
	event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== CACHE_NAME) {
					await caches.delete(key);
				}
			}
			await self.clients.claim();
		})
	);
});

self.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Don't cache Dropbox API calls
	if (url.hostname.includes('dropbox')) return;

	// Don't cache external requests
	if (url.origin !== self.location.origin) return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);

			// Try cache first for build assets (they're versioned/immutable)
			if (ASSETS.includes(url.pathname)) {
				const cached = await cache.match(event.request);
				if (cached) return cached;
			}

			// Network first for navigation requests
			try {
				const response = await fetch(event.request);
				// Cache successful responses
				if (response.status === 200) {
					cache.put(event.request, response.clone());
				}
				return response;
			} catch {
				// Offline — serve from cache
				const cached = await cache.match(event.request);
				if (cached) return cached;

				// For navigation requests, return the cached index page (SPA fallback)
				if (event.request.mode === 'navigate') {
					const fallback = await cache.match('/');
					if (fallback) return fallback;
				}

				return new Response('Offline', { status: 503 });
			}
		})()
	);
});
